---
title: "Big Classes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(dplyr)
library(janitor)
```

## R Markdown

```{r}
url_current <- "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_2.25.20_0.xlsx"

url_old <- "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_3.22.19_0.xlsx"

download.file(url = url_current,
              destfile = "current.xlsx")


download.file(url = url_old,
              destfile = "old.xlsx")

current <- read_excel("current.xlsx", skip = 3) %>% 
  clean_names() %>% 
  filter(!is.na(course_name))

old <- read_excel("old.xlsx", skip = 3) %>% 
  clean_names() %>% 
  filter(!is.na(course_name))

# Bring data together to select for courses that are new this year

new <- current %>% 
  anti_join(old, by = "course_id") %>% 
  arrange(desc(total)) %>% 
  select(course_name, total) %>% 
  slice(1:5)

```